// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa-4naTZh3830M7oMD1OJpGz-70CmIyVM',
    appId: '1:704397564191:web:8e9edff9551b501450782a',
    messagingSenderId: '704397564191',
    projectId: 'broomie-812da',
    authDomain: 'broomie-812da.firebaseapp.com',
    storageBucket: 'broomie-812da.firebasestorage.app',
    measurementId: 'G-V082TTVX9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5DI6iN0nxy4_x-aAejLGNq3B1lLDCqBI',
    appId: '1:704397564191:android:0b9f98962c1edaf650782a',
    messagingSenderId: '704397564191',
    projectId: 'broomie-812da',
    storageBucket: 'broomie-812da.firebasestorage.app',
  );

}